name: truckgo_project
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dotted_line: ^3.2.2
  dotted_border: ^2.0.0+3
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_rating_bar: ^4.0.1
  another_stepper: ^1.2.2
  sizer: ^2.0.15
  flutter_phone_direct_caller: ^2.1.1
  connectivity: ^3.0.6
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.0
  pin_code_fields: ^8.0.1
  flutter_dash: ^1.0.0
  image_picker: ^1.0.2
  google_maps_flutter: ^2.3.0
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    # - assets/images/order/
    # - assets/images/picking_point/
    # - assets/images/driver_info/

  fonts:
    - family: Avenir_Medium
      fonts:
        - asset: assets/fonts/Avenir_Medium.ttf
    - family: Avenir_Heavy
      fonts:
        - asset: assets/fonts/Avenir_Heavy.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
